from typing import Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

DEFAULT_UNIT = "um"


class PixelResolution(BaseModel):
    dimensions: tuple[float, ...]
    unit: str

    @classmethod
    def from_dimensions(cls, dimensions: tuple[float, ...]) -> Self:
        return cls(dimensions=dimensions, unit=DEFAULT_UNIT)


class N5ViewerArrayMetadata(BaseModel):
    """
    Preferred form, generated by n5-spark.

    <https://github.com/janelia-cellmap/schemas/blob/master/multiscale.md#modern-n5-viewer-style-source>
    """

    downsampling_factors: tuple[float, ...] | None = Field(
        None, alias="downsamplingFactors"
    )
    pixel_resolution: None | PixelResolution | tuple[float, ...] = Field(
        None, alias="pixelResolution"
    )
    model_config = ConfigDict(
        extra="allow",
    )

    @property
    def attributes(self):
        return self.__pydantic_extra__

    @model_validator(mode="after")
    def _validate_ndim(self) -> Self:
        if self.pixel_resolution is None or self.downsampling_factors is None:
            return self

        ds_ndim = len(self.downsampling_factors)
        if isinstance(self.pixel_resolution, PixelResolution):
            pr_ndim = len(self.pixel_resolution.dimensions)
        else:
            pr_ndim = len(self.pixel_resolution)

        if ds_ndim != pr_ndim:
            raise ValueError(
                f"Dimensionality of downsamplingFactors ({ds_ndim}) and pixelResolution ({pr_ndim}) does not match"
            )
        return self

    @property
    def resolution_unit(self) -> str | None:
        if self.pixel_resolution is None:
            return None
        elif isinstance(self.pixel_resolution, PixelResolution):
            return self.pixel_resolution.unit
        else:
            return DEFAULT_UNIT

    @property
    def resolution(self) -> tuple[float, ...] | None:
        if self.pixel_resolution is None:
            return None
        elif isinstance(self.pixel_resolution, PixelResolution):
            return self.pixel_resolution.dimensions
        else:
            return self.pixel_resolution

    def get_pixel_resolution(self) -> PixelResolution | None:
        if self.pixel_resolution is None:
            return None
        elif isinstance(self.pixel_resolution, PixelResolution):
            return self.pixel_resolution
        else:
            return PixelResolution.from_dimensions(self.pixel_resolution)


class N5ViewerGroupMetadata(BaseModel):
    """
    <https://github.com/janelia-cellmap/schemas/blob/master/multiscale.md#deprecated-n5-viewer-style-source>
    """

    resolution: tuple[float, ...] | None = None
    """Base pixel resolution, assumed to be in micrometers `um`."""
    pixel_resolution: PixelResolution | None = Field(None, alias="pixelResolution")
    """Base pixel resolution information."""
    scales: list[tuple[float, ...]] | None = None
    """Deprecated."""

    model_config = ConfigDict(
        extra="allow",
    )

    @model_validator(mode="after")
    def _validate_ndim(self) -> Self:
        resolutions = set()
        if r := self.resolution:
            resolutions.add(len(r))
        if pr := self.pixel_resolution:
            resolutions.add(len(pr.dimensions))
        if scales := self.scales:
            for s in scales:
                resolutions.add(len(s))

        if len(resolutions) > 1:
            raise ValueError("N5 Viewer group metadata has mismatched dimensions")
        return self

    def get_pixel_resolution(self) -> PixelResolution | None:
        if self.pixel_resolution is not None:
            return self.pixel_resolution
        elif self.resolution is not None:
            return PixelResolution.from_dimensions(self.resolution)
        return None
